// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_joke from "./routes/api/joke.ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $food from "./routes/food.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $images from "./routes/images.tsx";
import * as $index from "./routes/index.tsx";
import * as $subscriptions from "./routes/subscriptions.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $MobileNavToggle from "./islands/MobileNavToggle.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/joke.ts": $api_joke,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/food.tsx": $food,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/images.tsx": $images,
    "./routes/index.tsx": $index,
    "./routes/subscriptions.tsx": $subscriptions,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/MobileNavToggle.tsx": $MobileNavToggle,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
