// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $_404 from "./routes/_404.tsx";
import * as $_app from "./routes/_app.tsx";
import * as $api_auth_login from "./routes/api/auth/login.ts";
import * as $api_auth_logout from "./routes/api/auth/logout.ts";
import * as $api_dashboard_stats from "./routes/api/dashboard/stats.ts";
import * as $api_foods from "./routes/api/foods.ts";
import * as $api_foods_id_ from "./routes/api/foods/[id].ts";
import * as $api_health from "./routes/api/health.ts";
import * as $api_joke from "./routes/api/joke.ts";
import * as $api_stats from "./routes/api/stats.ts";
import * as $api_subscriptions from "./routes/api/subscriptions.ts";
import * as $api_subscriptions_id_ from "./routes/api/subscriptions/[id].ts";
import * as $dashboard from "./routes/dashboard.tsx";
import * as $demo from "./routes/demo.tsx";
import * as $food from "./routes/food.tsx";
import * as $greet_name_ from "./routes/greet/[name].tsx";
import * as $images from "./routes/images.tsx";
import * as $index from "./routes/index.tsx";
import * as $login from "./routes/login.tsx";
import * as $subscriptions from "./routes/subscriptions.tsx";
import * as $videos from "./routes/videos.tsx";
import * as $Counter from "./islands/Counter.tsx";
import * as $Dashboard from "./islands/Dashboard.tsx";
import * as $FoodManager from "./islands/FoodManager.tsx";
import * as $MobileNavToggle from "./islands/MobileNavToggle.tsx";
import * as $SubscriptionManager from "./islands/SubscriptionManager.tsx";
import type { Manifest } from "$fresh/server.ts";

const manifest = {
  routes: {
    "./routes/_404.tsx": $_404,
    "./routes/_app.tsx": $_app,
    "./routes/api/auth/login.ts": $api_auth_login,
    "./routes/api/auth/logout.ts": $api_auth_logout,
    "./routes/api/dashboard/stats.ts": $api_dashboard_stats,
    "./routes/api/foods.ts": $api_foods,
    "./routes/api/foods/[id].ts": $api_foods_id_,
    "./routes/api/health.ts": $api_health,
    "./routes/api/joke.ts": $api_joke,
    "./routes/api/stats.ts": $api_stats,
    "./routes/api/subscriptions.ts": $api_subscriptions,
    "./routes/api/subscriptions/[id].ts": $api_subscriptions_id_,
    "./routes/dashboard.tsx": $dashboard,
    "./routes/demo.tsx": $demo,
    "./routes/food.tsx": $food,
    "./routes/greet/[name].tsx": $greet_name_,
    "./routes/images.tsx": $images,
    "./routes/index.tsx": $index,
    "./routes/login.tsx": $login,
    "./routes/subscriptions.tsx": $subscriptions,
    "./routes/videos.tsx": $videos,
  },
  islands: {
    "./islands/Counter.tsx": $Counter,
    "./islands/Dashboard.tsx": $Dashboard,
    "./islands/FoodManager.tsx": $FoodManager,
    "./islands/MobileNavToggle.tsx": $MobileNavToggle,
    "./islands/SubscriptionManager.tsx": $SubscriptionManager,
  },
  baseUrl: import.meta.url,
} satisfies Manifest;

export default manifest;
